# DO NOT CHANGE THE NAME (e_demand),
#IF YOU WANT TO CHANGE THIS NAME, THEN YOU HAVE TO CHANGE THE EACH IMPORT STATEMENT IN THE CODE
#THIS NAME WILL NOT IMPACT IN YOUR APP, SO ITS NOT MANDATORY TO CHANGE IT
name: e_demand
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 11.7.0+82

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  intl: any
  connectivity_plus: ^6.0.5
  firebase_core: ^2.1.1
  pinput: ^5.0.0
  firebase_auth: ^4.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  share_plus: ^10.0.2
  dio: ^5.1.1
  cached_network_image: ^3.2.2
  shimmer: ^3.0.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.2.1
  custom_info_window: ^1.0.1
  image_picker: ^1.0.2
  firebase_messaging: ^14.1.2
  awesome_notifications: ^0.9.3+1
  app_settings: ^5.0.0
  flutter_svg: ^2.0.5
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^11.0.0
  firebase_core_platform_interface: ^5.2.0
  rive: ^0.13.4
  http_parser: ^4.0.2
  mime: ^1.0.3
  version: ^3.0.2
  url_launcher: ^6.1.7
  package_info_plus: ^8.0.2
  external_path: ^1.0.3
  open_filex: ^4.3.2
  path_provider: ^2.0.11
  webview_flutter: ^4.0.7
  change_app_package_name: ^1.1.0
  vibration: ^2.0.0
  quick_actions: ^1.0.2
  path: ^1.8.2
  video_player: ^2.6.1
  readmore: ^3.0.0
  flutter_widget_from_html: ^0.14.11
  image_cropper: ^8.0.2
  permission_handler: any
  lottie:
  file_picker:
  any_link_preview:
  shared_preferences: ^2.2.3
  flutter_shader_snap: ^0.0.3
  app_links: ^6.1.1
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0


dependency_overrides:
  pin_input_text_field: "4.5.0"
  intl: ^0.17.0
  chewie:
    git:
      url: https://github.com/mdeimert/chewie.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - packages/flutter_shader_snap/shaders/split_snap_effect_shader.glsl # add if you use SnapShaderType.split (default)
    - packages/flutter_shader_snap/shaders/split_reversed_snap_effect_shader.glsl # add if you use SnapShaderType.splitReversed
    - packages/flutter_shader_snap/shaders/smoke_snap_effect_shader.glsl # add if you use SnapShaderType.smoke

  assets:
    - assets/languages/
    - assets/images/
    - assets/images/branding/
    - assets/images/flags/
    - assets/mapTheme/
    - assets/animation/
    - assets/countryCodes/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
