// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBoUYJQ6HP31WRm8ZYMUXmDuMR-WaQ2I',
    appId: '1:220480348179:web:874129c8feccacd1841fe6',
    messagingSenderId: '220480348179',
    projectId: 'kimiiservicios',
    storageBucket: 'kimiiservicios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNBoUYJQ6HP31WRm8ZYMUXmDuMR-WaQ2I',
    appId: '1:220480348179:web:874129c8feccacd1841fe6',
    messagingSenderId: '220480348179',
    projectId: 'kimiiservicios',
    storageBucket: 'kimiiservicios.firebasestorage.app',
    androidClientId: '811828125363-2mfsj2tv7aju1l1dmgucjkip7r9jsfnk.apps.googleusercontent.com',
    iosClientId: '811828125363-vti0p1njla22jlpem03gblvvq0kkkds0.apps.googleusercontent.com',
    iosBundleId: 'com.kimiiservicios.kcore',
  );
}
